# [9] 예외처리

상태: 시작 전
날짜: 2024년 9월 29일
선택: 자바 문법 스터디

# 예외처리(Exception Handling)

## 프로그램의 오류(에러)

- 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우

### 발생 시점에 따른 구분

- 컴파일 에러(compile-time error)
    - 컴파일 도중 컴파일러가 발견하는 오류
    - 문법적 오류
- 런타임 에러(runtime error)
    - 컴파일은 성공적으로 진행되었으나, 프로그램 실행 중에 발생하는 오류
- 논리적 에러(logical error)
    - 컴파일도 되고 프로그램도 실행되었으나, 프로그램이 의도대로 동작하지 않는 오류
    - 프로그램이 정상적으로 실행되고 종료되었지만 결과가 예상과 다른 경우

### 에러와 예외

- 에러: 발생하면 복구할 수 없는 심각한 오류
    - 메모리 부족
    - 스택 오버 플로우
- 예외: 프로그래머가 적절한 코드를 통해 대비할 수 있는 오류
    - 클래스 형 변환 실패
    - 파일 읽기 실패

## 예외처리

- 예외 발생 시 프로그램의 비 정상 종료를 막고 정상적인 실행 상태를 유지하는 것
- 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요

### 예외 종류

- 체크 예외
    - 컴파일 시점에서 예외 처리가 요구되는 예외
    - `IOException`, `SQLException`
- 언체크 예외
    - 실행 시점에서 발생하는 예외
    - 컴파일러가 예외처리를 강제하지 않음
    - `NullPointerException` `ArrayIndexOutOfBoundsException`

### 예외 처리 키워드

- 직접 처리
    - `try {}`: 예외가 발생할 가능성이 있는 코드를 포함하는 블록
    - `catch (예외매개변수) {}`: 예외가 발생했을 때 실행할 코드 블록
    - `finally {}`: 예외 발생 여부와 상관없이 항상 실행되는 코드 블록
- 간접 처리(처리 위임)
    - `throws`: 메서드 시그니처에 사용되며, 해당 메서드가 특정 예외를 던질 수 있음을 명시
- 예외를 직접 발생시킬 때
    - `throw`: 예외를 명시적으로 발생시키는 키워드

## try~catch 구문

- 프로그램 실행 시 발생할 수 있는 예외에 대한 대비코드 작성
- 프로그램의 비정상적인 종료를 막고, 정상적인 상태를 유지할 수 있도록 함

```java
try {
	// 예외가 발생할 수 있는 코드
} catch (SomeException e){
	// 예외가 발생했을 때 처리할 코드
}
```

- 중괄호 생략 불가능
- 중첩 된 예외처리: 블록 안에 또 다른 try~catch 구문이 올 수 있음

### 다중 예외처리

- 예외 객체에 해당하는 catch 문장을 찾을 때는 **다형성**이 적용됨
- 상속 관계에서 상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음
- 상속 관계가 없는 경우는 무관
- 상속관계에서는 작은 범위(자식)에서 큰 범위(조상) 순으로 정의

### Exception 인스턴스의 주요 메서드

- `getMessage()`
    - 발생된 예외에 대한 구체적인 메시지를 반환
- `printStackTrace()`
    - 예외 발생 당시의 호출 스택(Call Stack)을 출력한다.

## 메서드에서 예외 던지기

- 메서드 선언부에 `throws` 키워드를 사용하여 예외 작성
- 예외가 여러 개일 경우 `,`를 이용하여 나열
- 메서드가 예외를 처리하는 것이 아닌 전달
- 조상 타입의 예외로 처리 가능(다형성)

```java
void method() throws Exception1, Exception2, ... ExceptionN {
	// 메서드 내용
}
```

메서드 선언부에 예외를 선언함으로써 메서드를 사용하려는 사람이 메서드의 선언부를 보고 이 메서드를 사용하기 위해서는 어떠한 예외들이 처리되어져야 하는지 알 수 있다.

### throws의 의미

1. (메서드를 정의하는 프로그래머) 
    
    이 메서드 내에서 이 예외를 처리하지 않고 이 메서드를 사용하는 사람이 예외를 처리해서 쓰도록
    
2. (이 메서드를 사용하는 프로그래머)
    
    이 메서드는 CheckedException을 발생시킬 수 있는 메서드이므로, 내가 이 예외를 처리해야겠다
    
3. (컴파일러)
    
    CheckedException은 원래 무조건 처리해야 하는데 이 메서드 본문 안에서는 봐줄게
    
- 만약 프로그램 시작점인 main 메서드 조차 throws한다면?

```java
public static void main(String[] args) throws Exception {
	method1();
} //main메서드의 끝

static void method1() throws Exception {
	method2();
} //method1의 끝

static void method2() throws Exception {
	throw new Exception();
} // method2의 끝
```

- method2()에서 `thorw new Exception();`문장에 의해 예외 강제 발생
- method2()가 종료되면서 예외를 method1()으로 전달
- method1()에서도 예외처리를 해주지 않았으므로 main메서드에 예외 전달

⇒ 결국에는 예외는 처리되지 않은 채 비정상적 종료가 된다.

### 메서드 재정의와 throws

- 메서드 재정의 시 조상클래스 메서드가 던지는 예외보다 부모 예외를 던질 수 없다.

## finally 구문

- finally는 예외 발생 여부와 상관 없이 언제나 실행

```java
try {
	// 예외가 발생할 가능성이 있는 코드
} catch(SomeException e){
	// 예외 처리 코드
} finally {
	// 예외 상관없이 항상 수행해야 하는 코드
}
```

- 예외 발생시: try→catch→finally
- 예외 미발생시: try→finally
- 중간에 return이 있어도 finally 블록 수행 후에 반환한다!

### 자동 자원 반납 구문(try with resources)

- 자원 등을 반납할 때 finally에서 close()를 통해 반납을 주로 함.
- 코드가 지저분해지고 다른 예외상황을 발생시킬 수 있음.
- `try()` ⇒ 괄호 안에 객체를 생성하는 코드를 작성하면, 해당 객체는 `close()`를 호출하지 않아도 블록을 벗어나는 순간 `close()`가 호출됨
- 해당 객체의 클래스가 `AutoCloseable`이라는 인터페이스를 구현한 클래스이어야 함.

```java
try (FileInputStrea fis = new FileInputStream("test.txt") {
	// 코드 생략
} catch (IOException e) {
	e.printStackTrace();
}
```

## 사용자 정의 예외

- 기존에 정의된 예외 이외에 사용자가 직접 정의 예외를 작성할 수 있음
- 대부분 Exception 또는 RuntimeException 클래스를 상속받아 작성
    - checked exception 활용
        - 명시적 예외 처리 또는 throws 필요
        - 코드는 복잡해지지만 처리, 누락 등 오류 발생 가능성은 down
    - runtime exception 활용
        - 묵시적 예외 처리 가능
        - 코드가 간결해지지만 예외 처리, 누락 가능성 발생